-- @deprecated ENTFERNT — 2026-03-13
--
-- Revenue Share Migration entfernt.
-- AIGG ist ein gemeinnuetziger Verein. Keine 50/50-Aufteilung, kein Revenue Waterfall.
-- Diese Datei wird beim naechsten Cleanup geloescht.
--
-- NICHT AUSFUEHREN.
